[project]
name = "yaytarch"
version = "1.0.0"
dependencies = [
    "flask", "yt-dlp"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []